from typing import Protocol, Sequence, Optional
from app.domain.entities.agent import Agent

class AgentRepository(Protocol):
    async def create(self, *, name:str, language:str, voice_type:str, active:bool=True) -> Agent: ...
    async def get(self, agent_id:int) -> Optional[Agent]: ...
    async def list(self) -> Sequence[Agent]: ...
    async def update_status(self, agent_id:int, active:bool) -> Agent: ...
