from typing import Protocol, Sequence, Optional, Mapping, Any
from app.domain.entities.call_log import CallLog

class CallRepository(Protocol):
    async def create_log(self, *, agent_id:int, driver_id:int|None, load_number:str, provider_call_id:str|None, call_outcome:str="queued", structured_payload:Mapping[str,Any]|None=None) -> CallLog: ...
    async def get(self, call_id:int) -> Optional[CallLog]: ...
    async def list_recent(self, limit:int=50) -> Sequence[CallLog]: ...
    async def update_status(self, call_id:int, *, call_outcome:str) -> CallLog: ...
    async def attach_structured_payload(self, call_id:int, *, payload:Mapping[str,Any]) -> CallLog: ...
